stages:
- name: build-dev
  steps:
  - publishImageConfig:
      dockerfilePath: ./docker/dev_elixir/Dockerfile
      buildContext: .
      tag: krini/cwlab:dev-${CICD_EXECUTION_SEQUENCE}
  when:
    branch:
      include:
      - development
- name: build-master
  steps:
  - publishImageConfig:
      dockerfilePath: ./docker/dev_elixir/Dockerfile
      buildContext: .
      tag: krini/cwlab:stable-${CICD_EXECUTION_SEQUENCE}
  when:
    branch:
      include:
      - master
- name: build-demo
  steps:
  - publishImageConfig:
      dockerfilePath: ./docker/dev_elixir/Dockerfile
      buildContext: .
      tag: krini/cwlab:demo-${CICD_EXECUTION_SEQUENCE}
  when:
    branch:
      include:
      - demo
- name: build-testing
  steps:
  - publishImageConfig:
      dockerfilePath: ./docker/dev_elixir/Dockerfile
      buildContext: .
      tag: krini/cwlab:testing-${CICD_EXECUTION_SEQUENCE}
  when:
    branch:
      include:
      - feature/testing
- name: deploy-dev
  steps:
  - applyYamlConfig:
      path: ./kube/develop-deployment.yaml
  when:
    branch:
      include:
      - development
- name: deploy-master
  steps:
  - applyYamlConfig:
      path: ./kube/stable-deployment.yaml
  when:
    branch:
      include:
      - master
- name: deploy-feature-testing
  steps:
  - applyYamlConfig:
      path: ./kube/testing-deployment.yaml
  when:
    branch:
      include:
      - feature/testing
- name: deploy-demo
  steps:
  - applyYamlConfig:
      path: ./kube/demo-deployment.yaml
  when:
    branch:
      include:
      - feature/demo
timeout: 60
notification: {}
